### ISSUE TITLE
Graph improvement

### ISSUE THREAD

**Issue by hram** [UnickSoft/graphonline#10]
Hi
First of all thank you for solution.
I was try to modify some behavior.
For example in my case I need to know vertex ID
I add opportunity to display vertex ID when vertex is selected and when I rename it.
![изображение](https://user-images.githubusercontent.com/2150637/83063753-51a50180-a069-11ea-9c27-5e04e4c12340.png)
![изображение](https://user-images.githubusercontent.com/2150637/83063799-5f5a8700-a069-11ea-8e5c-e5bf1499dde2.png)

And what I wery need is to add new algorithm but I do not know how (
Can you help me with my new algorithm?

PS when I click on algorithms button I have nothing (
![изображение](https://user-images.githubusercontent.com/2150637/83064132-fd4e5180-a069-11ea-94b7-73cb40188b5b.png)

**Comment by UnickSoft** [comment]
Hello.

Have you done this instruction:

`Run file from browser: /cgi-bin/getPluginsList.php?reset. It creates file with list of plug-ins. Just optimization. `

To add new algorithm you need place it into /script/plugins and run cgi-bin/getPluginsList.php?reset. After that it should appear in drop menu.

**Comment by hram** [comment]
Eys I do. And file in tmp dir with list of algorithms is exists.

**Comment by hram** [comment]
@UnickSoft I think I'v found problem
first time I set SiteDir without slash
`var SiteDir     = "graph";`
and when I fix it script dos not modify variable
when I edit file example.js algorithms list is fixed
`var SiteDir     = "graph/";`
