### ISSUE TITLE
Download failed font-family: "FontAwesome"

### ISSUE THREAD

**Issue by hram** [UnickSoft/graphonline#11]
downloadable font: download failed (font-family: "FontAwesome" style:normal weight:400 stretch:100 src index:1): status=2147746065 source: http://<my_domain>/i/fonts/dev/fontawesome/fontawesome-webfont.woff?v=4.0.3

I run graph from subdir "graph" and path for font need to be http://<my_domain>/**graph**/i/fonts/dev/fontawesome/fontawesome-webfont.woff?v=4.0.3

UPD: I changed file variables.less
`@fa-font-path:`        "/**graph**/i/fonts/dev/fontawesome";

and now error is gone

**Comment by UnickSoft** [comment]
Thanks. We will add information about it to readme.
