### ISSUE TITLE
Does the graph coloring uses greedy coloring method?

### ISSUE THREAD

**Issue by Bitsy-Chuck** [UnickSoft/graphonline#14]

**Comment by UnickSoft** [comment]
Yes. Coloring uses greedy coloring method.  You may look it here: https://github.com/UnickSoft/graphonline/blob/master/script/plugins/Coloring.js

**Comment by Bitsy-Chuck** [comment]
@UnickSoft So how is the chromatic number given? I could not find anything in the documentation, sorry

**Comment by UnickSoft** [comment]
You may look Greedy coloring on wiki: https://en.wikipedia.org/wiki/Greedy_coloring
We use the same algorithm, but we use many different ordering and choose the best variant with minimal number color.
