### ISSUE TITLE
Error in calculating the shortest path by Dijkstra's algorithm

### ISSUE THREAD

**Issue by kzkvv** [UnickSoft/graphonline#18]
See pic. Path should be as follows: 1->4->5->2 = 14+4+6 = 24 however, the calculator made a mistake and suggested the path 1->2 = 25

![image](https://user-images.githubusercontent.com/27914623/100922920-7d5ce480-34ef-11eb-83fe-e2e76dc97fdd.png)

the adjacency matrix for the similar graph:

0, 1, 1, 0, 0, 
0, 0, 0, 0, 1, 
0, 0, 0, 1, 0, 
0, 1, 0, 0, 0, 
0, 0, 0, 0, 0,

**Comment by UnickSoft** [comment]
Hello.
Looks like you use "Текст над дугой" to set weight of edge. Please try to use "Вес дуги" to set weight.
![Снимок экрана 2020-12-02 в 23 10 59](https://user-images.githubusercontent.com/9623833/100931878-c878f680-34f3-11eb-934c-0c4781bb611e.png) 
Weight of edge is drawn inside edge.
![Снимок экрана 2020-12-02 в 23 13 10](https://user-images.githubusercontent.com/9623833/100932078-0249fd00-34f4-11eb-903a-552078f078ff.png)

For this reason output result is 3 in text box for your case.

**Comment by kzkvv** [comment]
Yes, I made a mistake with the field selection in the modal window
