### ISSUE TITLE
Turn off New Graph hotkey or make it configurable

### ISSUE THREAD

**Issue by chekoopa** [UnickSoft/graphonline#2]
It is VERY easy to miss on the 'n' key when using 'm' (**mostly** 'm'),  'v' and 'e' hotkeys to work with the editor. Also, "new graph" operation can't be undone, it's kinda frustrating.

**Comment by UnickSoft** [comment]
Thanks for you feedback. We will fix it.

**Comment by UnickSoft** [comment]
I deleted 'n' hot-key, because it is rare use and user can use mouse to create graph.
