### ISSUE TITLE
Eulerian Cycle with isolated vertexes

### ISSUE THREAD

**Issue by gavrilikhin-d** [UnickSoft/graphonline#23]
Eulerian cycle visits every edge once. It must still exist if you add any number of isolated vertexes, which currently isn't true.

<details>
<summary>Example:</summary>

```
0, 1, 0, 0, 
0, 0, 1, 0, 
1, 0, 0, 0, 
0, 0, 0, 0, 
```
Expected: `0⇒1⇒2⇒0`
Actual: `Graph has not Eulerian cycle`
</details>

**Comment by UnickSoft** [comment]
Thanks.

**Comment by UnickSoft** [comment]
Fixed.
