### ISSUE TITLE
Implementing Ford-Bellman's algorithm.

### ISSUE THREAD

**Issue by Rassska** [UnickSoft/graphonline#24]
Hi, there!
I would like to add a very important algorithm that can help to find out shortest paths from source to all nodes of given graph. 

We already have Dijkstra algorithm that computes shortest way from one node to another, which means we are technically able to find shortest ways to all nodes, but it takes huge amount of time to consider all pairs single by single.

Need a quick response from your side, because I wanna implement it while I have holidays... =)

**Comment by UnickSoft** [comment]
Hello. Than would be nice, if you add new algorithm.

You may add new algorthm using C++ into our C++ module: https://github.com/UnickSoft/GraphOffline
or add using js. We can provide you some docs depends on  woch method will you choose.

**Comment by Rassska** [comment]
That's a great idea, I didn't know about C++ module at all and thought that I should to explore ```.php``` code =)
Okay, if I'll have some kind of misconceptions, I'll ask it here!

Have a good day :)
