### ISSUE TITLE
Select and move objects

### ISSUE THREAD

**Issue by gouhar1512** [UnickSoft/graphonline#3]
If we create two nodes (**1**, **2**) and select and drag node **2** over node **1**, then node **2** will lie above **1**.
But if we again double click on node **2** and try to drag it, then node **1** is selected and dragged, 
 not node **2**.

**Comment by UnickSoft** [comment]
Thanks. We will fix it.

**Comment by UnickSoft** [comment]
I changed select algorithm. Now it selects top object.
