### ISSUE TITLE
Arbitrary Styling of Vertices and Edges

### ISSUE THREAD

**Issue by Robin-Andrews** [UnickSoft/graphonline#35]
Feature request: It would be really helpful to be a be able to apply arbitrary styles to vertices and edges, rather than only having selected/common states. For example, when trying to illustrate Dijkstra's Algorithm, I need to highlight multiple edges at the same time.

**Comment by UnickSoft** [comment]
Hello. If I understund correct your feature request, we already have this feature. You can change selected / unselected styles for certain vertex or edges. Also you can use group selection to do this easy. Here is gif with demonstraion: https://graphonline.ru/en/wiki/uploads/Help/apply_styles.gif
