### ISSUE TITLE
Additional settings suggestions, and a typo.

### ISSUE THREAD

**Issue by Quasar-Nova-Ironfist** [UnickSoft/graphonline#42]
A few suggestions here. Firstly, ". Select first vertex of edge" has a period and extra space which "Select second vertext of edge" does not, though it does have an extra 't' in "vertex," which I assume was a typo. Additionally, the alignment of the two texts is different due to (I presume) the "Special actions" dropdown disappearing when the first vertex is selected, thus resulting in a shift in positioning for the text and the vertex selection boxes. Perhaps aligning relative to the left edge of the green box as opposed to the right would work better?

I have recommendations for two settings that could be added and seem (in my inexperience) relatively simple to add:
Firstly: an option to have the "Add edge" window not appear, instead automatically assuming a weight of zero and creating an edge, with it being directed or undirected depending on which one is selected (whichever was last created? Two toggles? One 3 option toggle for disabled, directed, and undirected?). If you were to implement such I would recommend having it not be inside the settings dropdown, but rather next to "Connect vertices," shifting the other buttons over some, due to it likely being used more often than the settings for changing colors. This would speed up the creation of unweighted graphs.
Secondly: a toggle for automatically setting the second vertex clicked to be the new first vertex in the next edge, allowing for slightly faster creation of large graphs, again not in the settings dropdown menu for the same reason.

And also, dark grey, or similar, as the default background color, as opposed to white. Perhaps an RGB of {77,77,77}?

**Comment by Quasar-Nova-Ironfist** [comment]
A probably less simple addition would be allowing for vertices that do not actually count as such for the purposes of the algorithms and do not require a label, instead being only to allow the organization of edges via detours, somewhat analogous to clips for cable management. As it stands now edges go (mostly) straight from vertex to vertex, sometimes causing excessively overlapping edges and visual clutter.

**Comment by UnickSoft** [comment]
Thanks. I will try to add your suggestions.

**Comment by UnickSoft** [comment]
We've fix typo issues and implemented feature for saving edge settings and reuse it on creating new one. We'll think about other ideas and will try to implement in future.
