### ISSUE TITLE
non-standard GraphML syntax for directed edges

### ISSUE THREAD

**Issue by nichtich** [UnickSoft/graphonline#50]
[GraphML edges](http://graphml.graphdrawing.org/specification/xsd.html#element-edge) are directed depending on edge attribute `directed` set to graph attribute `edgedefault` by default. Graphonline uses edge attribute `isDirect` instead and ignores graph attribute `edgedefault`. To maintain backwards compatibility, I'd recommend to support all three:

- `directed` (primary)
- `isDirect` (fallback) 
- `edgedefault` (else)

P.S: I'm surprised [the source code](https://github.com/UnickSoft/graphonline/blob/master/script/features/serialization/model/GraphMLCreator.js#L15) emits proper GraphML but the "export" feature at https://graphonline.ru/en/ returns a slightly different format with `isDirect` XML attribute?!

P.P.S: I think [this code](https://github.com/UnickSoft/graphonline/blob/master/script/entities/edge/model/BaseEdge.js#L57) is doing the wrong conversion from internal graph data to GraphML.

**Comment by UnickSoft** [comment]
Thanks. We will look it.
Indeed we have 2 exports for graphoffline utility and for user export.

**Comment by UnickSoft** [comment]
Fixed.
