### ISSUE TITLE
Self hosting error

### ISSUE THREAD

**Issue by hram** [UnickSoft/graphonline#6]
I was rtying to run graph on some domain in graph/ subdirectory
But main page is displayed so wrong
![изображение](https://user-images.githubusercontent.com/2150637/82816654-38068d00-9ea4-11ea-9499-8c9b3827489e.png)

**Comment by UnickSoft** [comment]
Hello. If it is possible, could you please attache log from browser and from server.
What browser do you use?
Check each steps from our readme. If it doesn't help you, try to disable GZIP (webserver cannot support it): unzip attached file and place it to /lib/ExtraPacker/ with replace.

[ExtraPacker.php.zip](https://github.com/UnickSoft/graphonline/files/4678414/ExtraPacker.php.zip)

**Comment by hram** [comment]
Позвольте я по русски напишу
Делал все как в редми
В 3-х файлах поправил путь к поддиректории 
Чтобы снизить вероятность ошибки директорию назвал так же как в документации

Мои правки в 3-х разных файлах:
RewriteRule ^(.*)$ /graph/index.php?q=$1 [L,QSA]
var SiteDir     = "graph/";
define('SITE_IN_DIR',   'graph');

При этом хочется отметить что скрипт merge.php не выполняется так как перебрасывает на https хотя я удалил строки которые отвечают за редирект на https

Логи браузера Firefox
![изображение](https://user-images.githubusercontent.com/2150637/82894465-49f73700-9f5b-11ea-8f59-28abd6cfc735.png)

**Comment by hram** [comment]
Заработало
Что я сделал

1. поменял права на папку tmp были права rw изменил на rwx из документации не понятно какие должны быть права, после этого появилась новая ошибка на загрузку стилей
2. Заменил ExtraPacker.php и все заработало

Спасибо за помощь.
Только лого почему то не прогрузилось
![изображение](https://user-images.githubusercontent.com/2150637/82897830-e8d26200-9f60-11ea-869c-6f15a3e1ed10.png)

**Comment by UnickSoft** [comment]
Спасибо. Внесём это в инструкцию.
